services:
  application:
    build: ..
    command: gunicorn {{cookiecutter.project_name}}.asgi:application -b 0.0.0.0:8000 -w 4 -k uvicorn.workers.UvicornWorker --log-level INFO
    container_name: "{{cookiecutter.project_name}}"
    environment:
      DEBUG: "True"
      SECRET_KEY: "a1b2c3d4e5f6g7h8i9j10k11l12m13n14o15p16q"
      SQLALCHEMY_DATABASE_URI: "sqlite:///db.sqlite3"
    image: app:${TAG:-local}
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/home/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/logs
